logging:
    version: 1
    disable_existing_loggers: False

    formatters:
        default:
            format: "[%(asctime)s] [%(levelname)s] [%(name)s] %(message)s"
            datefmt: "%Y-%m-%d %H:%M:%S"

    handlers:
        file:
            filename: logs/demo_app.log

    loggers:
        default:
            level: INFO
        requests:
            level: DEBUG
            propagate: False

        # Underlying HTTP transport used by requests
        urllib3:
            level: info
            propagate: False
            handlers: [console, file]
