site_name: pkg-infra
site_url: https://saezlab.github.io/pkg-infra
repo_url: https://github.com/saezlab/pkg-infra
repo_name: saezlab/pkg-infra

theme:
  name: material
  favicon: assets/favicon.ico
  icon:
    logo: material/database
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - assets/omnipath-theme.css

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
          options:
            show_source: false
            show_root_heading: true

nav:
  - Home: index.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - toc:
      permalink: true
